# Flight Price Prediction WebScrape

In [1]:
#Importing all necessary Libraries
import selenium
import pandas as pd
import numpy as np
from selenium import webdriver
from bs4 import BeautifulSoup
import requests
import time
from selenium.common.exceptions import NoSuchElementException,ElementNotInteractableException,ElementNotVisibleException
import re
import warnings
warnings.filterwarnings('ignore')

In [2]:
from selenium.webdriver.edge.service import Service

In [3]:
s = Service("msedgedriver.exe")

# Scraping Data From Yatra.com

In [4]:
url =  'https://www.yatra.com/'
driver = webdriver.Chrome(r"C:\Users\HP\Downloads\chromedriver_win32/chromedriver.exe")
driver.maximize_window() 
driver.get(url) #accessing the url on web driver
i=0
while(i<10):
   driver.execute_script("window.scrollBy(0,100)") # scroll down to get access to data for scraping
   i+=1

In [5]:
flturl =[] #creating an empty list which would contain all the scraped url

In [6]:
#Scraping all the necessary url data from which to scrape the required air fare data

flturl_tag = driver.find_elements_by_xpath("//a[@class='VueCarousel-slide items']")
for u in flturl_tag:
    try:
        flturl.append(u.get_attribute("href"))
    except:
        flturl.append('-')
        locbtn1 = driver.find_element_by_xpath('/html/body/div[2]/div/section/div[2]/div[2]/ul/li[2]')
        locbtn1.click()

In [7]:
for u in flturl_tag:
    try: 
        flturl.append(u.get_attribute("href"))
    except:
        flturl.append('-')
    time.sleep(1)
    
    locbtn2 = driver.find_element_by_xpath('/html/body/div[2]/div/section/div[2]/div[2]/ul/li[3]')
    locbtn2.click()

In [8]:
for u in flturl_tag:
    try: 
        flturl.append(u.get_attribute("href"))
    except:
        flturl.append('-')
    time.sleep(1)
    
    locbtn3 = driver.find_element_by_xpath('/html/body/div[2]/div/section/div[2]/div[2]/ul/li[4]')
    locbtn3.click()

In [9]:
for u in flturl_tag:
    try: 
        flturl.append(u.get_attribute("href"))
    except:
        flturl.append('-')
    time.sleep(1)
    
    locbtn4 = driver.find_element_by_xpath('/html/body/div[2]/div/section/div[2]/div[2]/ul/li[5]')
    locbtn4.click()

In [10]:
for u in flturl_tag:
    try: 
        flturl.append(u.get_attribute("href"))
    except:
        flturl.append('-')
    time.sleep(1)
    
    locbtn5 = driver.find_element_by_xpath('/html/body/div[2]/div/section/div[2]/div[2]/ul/li[6]')
    locbtn5.click()

In [11]:
for u in flturl_tag:
    try: 
        flturl.append(u.get_attribute("href"))
    except:
        flturl.append('-')
    time.sleep(1)

In [12]:
len(flturl)

120

In [13]:
flturl = [ x for x in flturl if "https://www.yatra.com/international-flights/" not in x ] #removing foreign flight links

In [14]:
len(flturl) #the list contains all important url data for web scraping

60

In [15]:
airline = [] #empty list to contain all the scraped airline names
fltnum= []  #empty list to contain all the scraped airline flight numbers
src= [] #empty list to contain all the scraped airline flight route data
deptdate = [] #empty list to contain all the scraped airline flight departure dates
stops= [] #empty list to contain all the scraped airline flight total stops
duration= []  #empty list to contain all the scraped airline flight duration
price= [] #empty list to contain all the scraped airline flight ticket price
n = [] #empty list to contain all the scraped url data for return flights

In [16]:
for l in flturl:
    driver.get(l) #loading the url on web driver
    time.sleep(4) # giving the webpage 4 seconds to load
    ltag= driver.find_elements_by_xpath("/html/body/div[3]/div[2]/div[3]/div[1]/div[1]/article/div[2]/strong[5]/a")

InvalidArgumentException: Message: invalid argument
  (Session info: chrome=98.0.4758.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x0064FDC3+2555331]
	Ordinal0 [0x005E77F1+2127857]
	Ordinal0 [0x004E2CD0+1060048]
	Ordinal0 [0x004D5763+1005411]
	Ordinal0 [0x004D45DD+1000925]
	Ordinal0 [0x004D46B6+1001142]
	Ordinal0 [0x004E43FA+1065978]
	Ordinal0 [0x00537BAD+1407917]
	Ordinal0 [0x00527B0C+1342220]
	Ordinal0 [0x005375FA+1406458]
	Ordinal0 [0x00527976+1341814]
	Ordinal0 [0x005036B6+1193654]
	Ordinal0 [0x00504546+1197382]
	GetHandleVerifier [0x007E9622+1619522]
	GetHandleVerifier [0x0089882C+2336844]
	GetHandleVerifier [0x006E23E1+541697]
	GetHandleVerifier [0x006E1443+537699]
	Ordinal0 [0x005ED18E+2150798]
	Ordinal0 [0x005F1518+2168088]
	Ordinal0 [0x005F1660+2168416]
	Ordinal0 [0x005FB330+2208560]
	BaseThreadInitThunk [0x7796FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DA7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77DA7A6E+238]

In [36]:
for u in ltag:
    try: 
        n.append(u.get_attribute("href")) 
    except:
         n.append('-') #finds all url elements of return flights and appends them to the empty list
    try:
        airlinetag = driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
        for i in airlinetag:
            airline.append(i.text) #finds all airline name elements and appends them to airline list
    except:
        airline.append('-')
        
    try:
        fltnumtag = driver.find_elements_by_xpath("//p[@class ='normal fs-11 font-lightestgrey no-wrap fl-no']/span")
for i in fltnumtag: 
          fltnum.append(i.text) #finds all airline flightnumber elements and appends them to flightnumber list
    except:
        fltnum.append('-')   
    try:
        srctag = driver.find_elements_by_xpath("//p[@class ='fs-10 font-lightgrey no-wrap city ellipsis']")
for i in srctag:
            src.append(i.text) #finds all airline route elements and appends them to src list
    except:
        src.append('-')
        
    try:
        stopstag = driver.find_elements_by_xpath("//span[@class='dotted-borderbtm' or @class='cursor-default']")
for i in stopstag:
            stops.append(i.text) #finds all airline flight total stops elements and appends them to stops list
    except:
        stops.append('-')
    try:
        durationtag = driver.find_elements_by_xpath("//p[@class ='fs-12 bold du mb-2']")
for i in durationtag:
            duration.append(i.text) #finds all airline flight duration elements and appends them to duration list
    except:
        duration.append('-')
    
    try:
        pricetag = driver.find_elements_by_xpath("//div[@class ='i-b tipsy fare-summary-tooltip fs-18']")
for i in pricetag:
            price.append(i.text) #finds all airline flight ticket price elements and appends them to price list
    except:
        price.append('-')
      
    try:
        deptdatetag = driver.find_element_by_xpath("//span[@class ='lowestDate']")
for i in range(0,10):
            deptdate.append(deptdatetag.text) #Appends the flight date element of the current url 
                                                 #web page for 10 times to deptdate list and repeats for every url webpage
    except:
        deptdate.append('-')

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 17)

In [37]:
#Extracting Air Fare Data from URL webpages of return flights, program functions exactly same as above

for l in n:
    driver.get(l)
    time.sleep(4)
    
    try:
        airlinetag = driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
        for i in airlinetag:
            airline.append(i.text)
    except:
        airline.append('-')
        
    try:
        fltnumtag = driver.find_elements_by_xpath("//p[@class ='normal fs-11 font-lightestgrey no-wrap fl-no']/span")
        for i in fltnumtag:
          fltnum.append(i.text)
    except:
        fltnum.append('-')   
    try:
        srctag = driver.find_elements_by_xpath("//p[@class ='fs-10 font-lightgrey no-wrap city ellipsis']")
        for i in srctag:
            src.append(i.text)
    except:
        src.append('-')
        
    try:
        stopstag = driver.find_elements_by_xpath("//span[@class='dotted-borderbtm' or @class='cursor-default']")
        for i in stopstag:
            stops.append(i.text)
    except:
        stops.append('-')
    try:
        durationtag = driver.find_elements_by_xpath("//p[@class ='fs-12 bold du mb-2']")
        for i in durationtag:
            duration.append(i.text)
    except:
        duration.append('-')
    
    try:
        pricetag = driver.find_elements_by_xpath("//div[@class ='i-b tipsy fare-summary-tooltip fs-18']")
        for i in pricetag:
            price.append(i.text)
    except:
        price.append('-')
      
    try:
        deptdatetag = driver.find_element_by_xpath("//span[@class ='lowestDate']")
        for i in range(0,10):
            deptdate.append(deptdatetag.text)
    except:
        deptdate.append('-')

In [38]:
dest=[] #empty list to contain destination location data
source=[] #empty list to contain source location data
for i in range(0,len(src),2):  
    source.append(src[i])
for i in range(1,len(src),2):
    dest.append(src[i]) #splits the data elements in src list into source and destination data elements
                           #and appends them to source and destination lists respectively

In [39]:
#Creating FlightDF Data Frame with the scraped data
FlightDF= pd.DataFrame({'Airline':airline,'Flight Number':fltnum,'Date of Departure':deptdate[0:1175],'From':source,'To':dest,'Duration':duration,'Total Stops':stops,'Price':price})

ValueError: arrays must all be same length

In [40]:
FlightDF

,Unnamed: 0,Airline,Flight Number,Date of Departure,From,To,Duration,Total Stops,Price
0,0,Air Asia,I5-764,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
1,1,IndiGo,6E-2054,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
2,2,IndiGo,6E-5001,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
3,3,IndiGo,6E-2046,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
4,4,IndiGo,6E-5328,"Tue, Feb 8",New Delhi,Mumbai,2h 15m,Non Stop,"2,456"
...,...,...,...,...,...,...,...,...,...
2580,2580,Vistara,UK-613,Dec-07,Mumbai,Bangalore,08h 10m,2+-stop,"15,581"
2581,2581,Vistara,UK-653,Dec-07,Mumbai,Bangalore,12h 15m,1-stop,"15,603"
2582,2582,Air India,AI-675,Dec-07,Mumbai,Bangalore,17h 10m,1-stop,"15,498"
2583,2583,Vistara,UK-651,Dec-07,Mumbai,Bangalore,26h 10m,1-stop,"17,283"
2584,2584,Vistara,UK-930,Dec-07,Mumbai,Bangalore,08h 30m,1-stop,"19,593"

In [41]:
FlightDF.to_csv('FlightData.csv') #Saving as .csv file

# Scraping Data from EaseMyTrip

In [17]:
url =  'https://www.easemytrip.com/?utm_source=google&utm_medium=cpc&utm_campaign=14425253924&utm_content=128139253602&utm_term=easemytrip&utm_campaign=14425253924&utm_source=g_c&utm_medium=cpc&utm_term=e_easemytrip&adgroupid=128139253602&gclid=CjwKCAiAqIKNBhAIEiwAu_ZLDlT5YOtVqr_cBvopvRV97poc_Qf54b5aTshxY-ho9drT4c4ICLdOLBoC8YcQAvD_BwE'
driver = webdriver.Chrome(r"C:\Users\HP\Downloads\chromedriver_win32/chromedriver.exe")
driver.maximize_window() 
driver.get(url) #accessing the url on web driver

In [18]:
#Storing the required urls for web scraping in a list
n = ['https://flight.easemytrip.com/FlightList/Index?org=DEL-Delhi,%20India%20,&dept=BOM-Mumbai,%20India%20,&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=28/11/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL=','https://flight.easemytrip.com/FlightList/Index?org=BOM-Mumbai,%20India%20,&dept=DEL-Delhi,%20India%20,&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=29/11/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL=','https://flight.easemytrip.com/FlightList/Index?org=DEL-Delhi,%20India%20,&dept=GOI-Goa,%20India%20,&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=30/11/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL=','https://flight.easemytrip.com/FlightList/Index?org=DEL-Delhi,%20India%20,&dept=BLR-Bangalore,%20India%20,&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=01/12/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL=','https://flight.easemytrip.com/FlightList/Index?org=BOM-Mumbai,%20India%20,&dept=GOI-Goa,%20India%20,&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=02/12/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL=','https://flight.easemytrip.com/FlightList/Index?org=DEL-Delhi,%20India%20,&dept=PAT-Patna,%20India%20,&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=03/12/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL=','https://flight.easemytrip.com/FlightList/Index?org=DEL-Delhi,%20India%20,&dept=CCU-Kolkata,%20India%20,&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=04/12/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL=','https://flight.easemytrip.com/FlightList/Index?org=DEL-Delhi,%20India%20,&dept=PNQ-Pune,%20India%20,&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=05/12/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL=','https://flight.easemytrip.com/FlightList/Index?org=CCU-Kolkata,%20India%20,&dept=DEL-Delhi,%20India%20,&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=06/12/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL=','https://flight.easemytrip.com/FlightList/Index?org=BOM-Mumbai,%20India%20,&dept=BLR-Bangalore,%20India%20,&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=07/12/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL=']

In [19]:
airline = [] #empty list to contain all the scraped airline names
fltnum= []  #empty list to contain all the scraped airline flight numbers
src= [] #empty list to contain all the scraped airline flight route data
deptdate = [] #empty list to contain all the scraped airline flight departure dates
stops= [] #empty list to contain all the scraped airline flight total stops
duration= [] #empty list to contain all the scraped airline flight duration
price= [] #empty list to contain all the scraped airline flight ticket price

In [20]:
for l in n:
    driver.get(l)#loading the url on web driver
    time.sleep(4) # giving the webpage 4 seconds to load
    
    try:
        airlinetag = driver.find_elements_by_xpath("//span[@class='txt-r4 ng-binding']")
        for i in airlinetag:
            airline.append(i.text)#finds all airline name elements and appends them to airline list
            
    except:
        airline.append('-')
        al.append('-')
    try:
        fltnumtag = driver.find_elements_by_xpath("//span[@class ='txt-r5']")
        for i in fltnumtag:   #finds all airline flightnumber elements and appends them to flightnumber list
          fltnum.append(i.text)
    except:
        fltnum.append('-')   
    try:
        srctag = driver.find_elements_by_xpath("//span[@class ='txt-r3-n ng-binding']")
        for i in srctag:
            src.append(i.text) #finds all airline route elements and appends them to src list
    except:
        src.append('-')
        
    try:
        stopstag = driver.find_elements_by_xpath("//span[@class='dura_md2 ng-scope']")
        for i in stopstag:
            stops.append(i.text) #finds all airline flight total stops elements and appends them to stops list
    except:
        stops.append('-')
    try:
        durationtag = driver.find_elements_by_xpath("//span[@class ='dura_md ng-binding']")
        for i in durationtag:
            duration.append(i.text) #finds all airline flight duration elements and appends them to duration list
    except:
        duration.append('-')
    
    try:
        pricetag = driver.find_elements_by_xpath("//div[@class ='col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding']")
        for i in pricetag:
            price.append(i.text) #finds all airline flight ticket price elements and appends them to price list
    except:
        price.append('-')

In [22]:
for l in n:
    driver.get(l)
    time.sleep(4)
    al=[] # an empty list to append airline names to be used later for scraping Date data
    try:
        airlinetag = driver.find_elements_by_xpath("//span[@class='txt-r4 ng-binding']")
        for i in airlinetag:
            al.append(i.text)#finds all airline name elements and appends them to al list
            
    except:
        
        al.append('-')
    try:
        deptdatetag = driver.find_element_by_xpath("//*[@id='jssor_1']/div/div/div/div/div[2]/div[6]/div[1]/div[1]/div[1]")
        for i in range(0,len(al)):
            deptdate.append(deptdatetag.text) 
    except:
        deptdate.append('-') 
#Appends the flight date element of the current url web page for total number of airline names on the webpage to deptdate list and repeats for every url webpage

In [23]:
Price = list(filter(None, price))#removing blank elements from list

In [24]:
dest=[] #empty list to contain destination location data
source=[]#empty list to contain source location data
for i in range(0,len(src),2):
    source.append(src[i])
for i in range(1,len(src),2):
    dest.append(src[i])
#splits the data elements in src list into source and destination data elements and appends them to source and destination lists respectively.

In [42]:
#Creating FlightDF Data Frame with the scraped data
FlightDF2= pd.DataFrame({'Airline':airline,'Flight Number':fltnum,'Date of Departure':deptdate[0:1410],'From':source,'To':dest,'Duration':duration,'Total Stops':stops,'Price':Price})

ValueError: arrays must all be same length

In [43]:
FlightDF2

Empty DataFrame
Columns: [Airline, Flight Number, Date of Departure, From, To, Duration, Total Stops, Price]
Index: []

# Combining the 2 DataFrames

In [44]:
FlightDF =  pd.read_csv('FlightData.csv')

In [45]:
FlightDF

,Unnamed: 0,Unnamed: 0.1,Airline,Flight Number,Date of Departure,From,To,Duration,Total Stops,Price
0,0,0,Air Asia,I5-764,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
1,1,1,IndiGo,6E-2054,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
2,2,2,IndiGo,6E-5001,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
3,3,3,IndiGo,6E-2046,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
4,4,4,IndiGo,6E-5328,"Tue, Feb 8",New Delhi,Mumbai,2h 15m,Non Stop,"2,456"
...,...,...,...,...,...,...,...,...,...,...
2580,2580,2580,Vistara,UK-613,Dec-07,Mumbai,Bangalore,08h 10m,2+-stop,"15,581"
2581,2581,2581,Vistara,UK-653,Dec-07,Mumbai,Bangalore,12h 15m,1-stop,"15,603"
2582,2582,2582,Air India,AI-675,Dec-07,Mumbai,Bangalore,17h 10m,1-stop,"15,498"
2583,2583,2583,Vistara,UK-651,Dec-07,Mumbai,Bangalore,26h 10m,1-stop,"17,283"
2584,2584,2584,Vistara,UK-930,Dec-07,Mumbai,Bangalore,08h 30m,1-stop,"19,593"

In [46]:
FlightData = pd.concat([FlightDF,FlightDF2],ignore_index=True)

In [47]:
FlightData

,Unnamed: 0,Unnamed: 0.1,Airline,Flight Number,Date of Departure,From,To,Duration,Total Stops,Price
0,0.0,0.0,Air Asia,I5-764,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
1,1.0,1.0,IndiGo,6E-2054,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
2,2.0,2.0,IndiGo,6E-5001,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
3,3.0,3.0,IndiGo,6E-2046,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
4,4.0,4.0,IndiGo,6E-5328,"Tue, Feb 8",New Delhi,Mumbai,2h 15m,Non Stop,"2,456"
...,...,...,...,...,...,...,...,...,...,...
2580,2580.0,2580.0,Vistara,UK-613,Dec-07,Mumbai,Bangalore,08h 10m,2+-stop,"15,581"
2581,2581.0,2581.0,Vistara,UK-653,Dec-07,Mumbai,Bangalore,12h 15m,1-stop,"15,603"
2582,2582.0,2582.0,Air India,AI-675,Dec-07,Mumbai,Bangalore,17h 10m,1-stop,"15,498"
2583,2583.0,2583.0,Vistara,UK-651,Dec-07,Mumbai,Bangalore,26h 10m,1-stop,"17,283"
2584,2584.0,2584.0,Vistara,UK-930,Dec-07,Mumbai,Bangalore,08h 30m,1-stop,"19,593"

In [48]:
FlightData.drop(columns=['Unnamed: 0'],inplace=True) #dropping Unnamed: 0 column

In [49]:
FlightData.to_csv('FlightData.csv') # Saving as .csv file

In [50]:
FlightData

,Unnamed: 0.1,Airline,Flight Number,Date of Departure,From,To,Duration,Total Stops,Price
0,0.0,Air Asia,I5-764,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
1,1.0,IndiGo,6E-2054,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
2,2.0,IndiGo,6E-5001,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
3,3.0,IndiGo,6E-2046,"Tue, Feb 8",New Delhi,Mumbai,2h 10m,Non Stop,"2,456"
4,4.0,IndiGo,6E-5328,"Tue, Feb 8",New Delhi,Mumbai,2h 15m,Non Stop,"2,456"
...,...,...,...,...,...,...,...,...,...
2580,2580.0,Vistara,UK-613,Dec-07,Mumbai,Bangalore,08h 10m,2+-stop,"15,581"
2581,2581.0,Vistara,UK-653,Dec-07,Mumbai,Bangalore,12h 15m,1-stop,"15,603"
2582,2582.0,Air India,AI-675,Dec-07,Mumbai,Bangalore,17h 10m,1-stop,"15,498"
2583,2583.0,Vistara,UK-651,Dec-07,Mumbai,Bangalore,26h 10m,1-stop,"17,283"
2584,2584.0,Vistara,UK-930,Dec-07,Mumbai,Bangalore,08h 30m,1-stop,"19,593"